sonar.projectKey=c3d-client
sonar.sources=src/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**,coverage/**,**/utils/protos/**,**/workers/**
sonar.coverage.exclusions=**/*.test.*,**/*.config.*,**/utils/protos/**,**/workers/**
sonar.host.url=http://localhost:9000