sonar.projectKey=c3d-client
sonar.sources=src/
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**,coverage/**
sonar.coverage.exclusions=**/*.test.*,**/protos/**
sonar.host.url=http://localhost:9000