// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: aydDirek.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface AydDirekResponse {
  isSuccess: boolean;
  message: string;
  statusCode: number;
  data: AydDirekProto[];
}

export interface AydDirekProto {
  id: number;
  kodu: string;
  adi: string;
  cinsi: string;
  tipi: string;
  direkNo: string;
  boyOzellik: string;
  direkBoyId: number;
  wkb: string;
}

function createBaseAydDirekResponse(): AydDirekResponse {
  return { isSuccess: false, message: "", statusCode: 0, data: [] };
}

export const AydDirekResponse: MessageFns<AydDirekResponse> = {
  encode(message: AydDirekResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSuccess !== false) {
      writer.uint32(8).bool(message.isSuccess);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.statusCode !== 0) {
      writer.uint32(24).int32(message.statusCode);
    }
    for (const v of message.data) {
      AydDirekProto.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AydDirekResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAydDirekResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSuccess = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.statusCode = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data.push(AydDirekProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AydDirekResponse {
    return {
      isSuccess: isSet(object.isSuccess) ? globalThis.Boolean(object.isSuccess) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      statusCode: isSet(object.statusCode) ? globalThis.Number(object.statusCode) : 0,
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => AydDirekProto.fromJSON(e)) : [],
    };
  },

  toJSON(message: AydDirekResponse): unknown {
    const obj: any = {};
    if (message.isSuccess !== false) {
      obj.isSuccess = message.isSuccess;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.statusCode !== 0) {
      obj.statusCode = Math.round(message.statusCode);
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => AydDirekProto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AydDirekResponse>, I>>(base?: I): AydDirekResponse {
    return AydDirekResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AydDirekResponse>, I>>(object: I): AydDirekResponse {
    const message = createBaseAydDirekResponse();
    message.isSuccess = object.isSuccess ?? false;
    message.message = object.message ?? "";
    message.statusCode = object.statusCode ?? 0;
    message.data = object.data?.map((e) => AydDirekProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAydDirekProto(): AydDirekProto {
  return { id: 0, kodu: "", adi: "", cinsi: "", tipi: "", direkNo: "", boyOzellik: "", direkBoyId: 0, wkb: "" };
}

export const AydDirekProto: MessageFns<AydDirekProto> = {
  encode(message: AydDirekProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.kodu !== "") {
      writer.uint32(18).string(message.kodu);
    }
    if (message.adi !== "") {
      writer.uint32(26).string(message.adi);
    }
    if (message.cinsi !== "") {
      writer.uint32(34).string(message.cinsi);
    }
    if (message.tipi !== "") {
      writer.uint32(42).string(message.tipi);
    }
    if (message.direkNo !== "") {
      writer.uint32(50).string(message.direkNo);
    }
    if (message.boyOzellik !== "") {
      writer.uint32(58).string(message.boyOzellik);
    }
    if (message.direkBoyId !== 0) {
      writer.uint32(65).double(message.direkBoyId);
    }
    if (message.wkb !== "") {
      writer.uint32(74).string(message.wkb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AydDirekProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAydDirekProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kodu = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.adi = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cinsi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tipi = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.direkNo = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.boyOzellik = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.direkBoyId = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.wkb = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AydDirekProto {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      kodu: isSet(object.kodu) ? globalThis.String(object.kodu) : "",
      adi: isSet(object.adi) ? globalThis.String(object.adi) : "",
      cinsi: isSet(object.cinsi) ? globalThis.String(object.cinsi) : "",
      tipi: isSet(object.tipi) ? globalThis.String(object.tipi) : "",
      direkNo: isSet(object.direkNo) ? globalThis.String(object.direkNo) : "",
      boyOzellik: isSet(object.boyOzellik) ? globalThis.String(object.boyOzellik) : "",
      direkBoyId: isSet(object.direkBoyId) ? globalThis.Number(object.direkBoyId) : 0,
      wkb: isSet(object.wkb) ? globalThis.String(object.wkb) : "",
    };
  },

  toJSON(message: AydDirekProto): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.kodu !== "") {
      obj.kodu = message.kodu;
    }
    if (message.adi !== "") {
      obj.adi = message.adi;
    }
    if (message.cinsi !== "") {
      obj.cinsi = message.cinsi;
    }
    if (message.tipi !== "") {
      obj.tipi = message.tipi;
    }
    if (message.direkNo !== "") {
      obj.direkNo = message.direkNo;
    }
    if (message.boyOzellik !== "") {
      obj.boyOzellik = message.boyOzellik;
    }
    if (message.direkBoyId !== 0) {
      obj.direkBoyId = message.direkBoyId;
    }
    if (message.wkb !== "") {
      obj.wkb = message.wkb;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AydDirekProto>, I>>(base?: I): AydDirekProto {
    return AydDirekProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AydDirekProto>, I>>(object: I): AydDirekProto {
    const message = createBaseAydDirekProto();
    message.id = object.id ?? 0;
    message.kodu = object.kodu ?? "";
    message.adi = object.adi ?? "";
    message.cinsi = object.cinsi ?? "";
    message.tipi = object.tipi ?? "";
    message.direkNo = object.direkNo ?? "";
    message.boyOzellik = object.boyOzellik ?? "";
    message.direkBoyId = object.direkBoyId ?? 0;
    message.wkb = object.wkb ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
