services:
  auth_database:
    image: postgres:17
    container_name: auth_database
    # Remove the ports section when deploying
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASS}
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - gis_db_connection
    restart: unless-stopped

  buildings_database:
    image: postgis/postgis:17-master
    container_name: buildings_database
    # Remove the ports section when deploying
    ports:
      - "6001:5432"
    environment:
      - POSTGRES_DB=${BUILDINGS_DB_NAME}
      - POSTGRES_USER=${BUILDINGS_DB_USER}
      - POSTGRES_PASSWORD=${BUILDINGS_DB_PASS}
    volumes:
      - buildings_data:/var/lib/postgresql/data
    networks:
      - gis_db_connection
    restart: unless-stopped

  poles_database:
    image: postgis/postgis:17-master
    container_name: poles_database
    # Remove the ports section when deploying
    ports:
      - "6002:5432"
    environment:
      - POSTGRES_DB=${POLES_DB_NAME}
      - POSTGRES_USER=${POLES_DB_USER}
      - POSTGRES_PASSWORD=${POLES_DB_PASS}
    volumes:
      - poles_data:/var/lib/postgresql/data
    networks:
      - gis_db_connection
    restart: unless-stopped

  lines_database:
    image: postgis/postgis:17-master
    container_name: lines_database
    # Remove the ports section when deploying
    ports:
      - "6003:5432"
    environment:
      - POSTGRES_DB=${LINES_DB_NAME}
      - POSTGRES_USER=${LINES_DB_USER}
      - POSTGRES_PASSWORD=${LINES_DB_PASS}
    volumes:
      - lines_data:/var/lib/postgresql/data
    networks:
      - gis_db_connection
    restart: unless-stopped

  auth_service:
    build:
      context: .
      dockerfile: Services/AuthService/Dockerfile
    container_name: auth_service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - POSTGRESQL_CONNECTION_STRING=Host=auth_database;Database=${AUTH_DB_NAME};Username=${AUTH_DB_USER};Password=${AUTH_DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_TIME_HRS=${JWT_EXPIRATION_TIME_HRS}
    depends_on:
      - auth_database
    networks:
      - gis_db_connection
      - api_gateway_network
    # ports:
    #   - "5000:8080"
    restart: unless-stopped

  buildings_service:
    build:
      context: .
      dockerfile: Services/BuildingsService/Dockerfile
    container_name: buildings_service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - POSTGRESQL_CONNECTION_STRING=Host=buildings_database;Database=${BUILDINGS_DB_NAME};Username=${BUILDINGS_DB_USER};Password=${BUILDINGS_DB_PASS}
    depends_on:
      - buildings_database
    networks:
      - gis_db_connection
      - api_gateway_network
    # ports:
    #   - "5001:8080"
    restart: unless-stopped
        
  poles_service:
    build:
      context: .
      dockerfile: Services/PolesService/Dockerfile
    container_name: poles_service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - POSTGRESQL_CONNECTION_STRING=Host=poles_database;Database=${POLES_DB_NAME};Username=${POLES_DB_USER};Password=${POLES_DB_PASS}
    depends_on:
      - poles_database
    networks:
      - gis_db_connection
      - api_gateway_network
    # ports:
    #   - "5003:8080"
    restart: unless-stopped

  lines_service:
    build:
      context: .
      dockerfile: Services/LinesService/Dockerfile
    container_name: lines_service
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - POSTGRESQL_CONNECTION_STRING=Host=lines_database;Database=${LINES_DB_NAME};Username=${LINES_DB_USER};Password=${LINES_DB_PASS}
    depends_on:
      - lines_database
    networks:
      - gis_db_connection
      - api_gateway_network
    # ports:
    #   - "5002:8080"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_TILE_SERVER_URL: ${VITE_TILE_SERVER_URL}
    container_name: client
    networks:
      - api_gateway_network
    restart: unless-stopped

  tile_server:
    image: maplibre/martin:main
    container_name: tile_server
    networks:
      - api_gateway_network
    # ports: 
    #   - "3001:3000"
    volumes:
      - tile_data:/tileData
      - ./TileService/config.yml:/tileData/config.yml
    command: ["--config", "/tileData/config.yml"]
    restart: unless-stopped

  api_gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api_gateway
    environment:
      - JWT_SECRET_BASE64=${JWT_SECRET_BASE64}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_TIME_HRS=${JWT_EXPIRATION_TIME_HRS}
      - BASE_URL=${BASE_URL}
    networks:
      - api_gateway_network
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./ApiGateway/Caddyfile:/etc/caddy/Caddyfile
      - ./ApiGateway/docs.html:/usr/share/caddy/docs.html
      - ./ApiGateway/localhost.crt:/usr/share/caddy/localhost.crt
      - ./ApiGateway/localhost.key:/usr/share/caddy/localhost.key
      - caddy_data:/data
    restart: unless-stopped

networks:
  # Service - Database connection network
  gis_db_connection:
    driver: bridge
  # Api Gateway - Service connection network
  api_gateway_network:
    driver: bridge

volumes:
  buildings_data:
  lines_data:
  poles_data:
  auth_data:
  caddy_data:
  tile_data:
  