// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: adrBina.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface AdrBinaResponse {
  isSuccess: boolean;
  message: string;
  statusCode: number;
  data: AdrBinaProto[];
}

export interface AdrBinaProto {
  id: number;
  kodu: string;
  siteAdi: string;
  adi: string;
  binaKatSayisi: number;
  daireSayisi: number;
  isyeriSayisi: number;
  yukseklik: number;
  wkb: string;
}

function createBaseAdrBinaResponse(): AdrBinaResponse {
  return { isSuccess: false, message: "", statusCode: 0, data: [] };
}

export const AdrBinaResponse: MessageFns<AdrBinaResponse> = {
  encode(message: AdrBinaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSuccess !== false) {
      writer.uint32(8).bool(message.isSuccess);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.statusCode !== 0) {
      writer.uint32(24).int32(message.statusCode);
    }
    for (const v of message.data) {
      AdrBinaProto.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AdrBinaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAdrBinaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSuccess = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.statusCode = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data.push(AdrBinaProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AdrBinaResponse {
    return {
      isSuccess: isSet(object.isSuccess) ? globalThis.Boolean(object.isSuccess) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      statusCode: isSet(object.statusCode) ? globalThis.Number(object.statusCode) : 0,
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => AdrBinaProto.fromJSON(e)) : [],
    };
  },

  toJSON(message: AdrBinaResponse): unknown {
    const obj: any = {};
    if (message.isSuccess !== false) {
      obj.isSuccess = message.isSuccess;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.statusCode !== 0) {
      obj.statusCode = Math.round(message.statusCode);
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => AdrBinaProto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AdrBinaResponse>, I>>(base?: I): AdrBinaResponse {
    return AdrBinaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AdrBinaResponse>, I>>(object: I): AdrBinaResponse {
    const message = createBaseAdrBinaResponse();
    message.isSuccess = object.isSuccess ?? false;
    message.message = object.message ?? "";
    message.statusCode = object.statusCode ?? 0;
    message.data = object.data?.map((e) => AdrBinaProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAdrBinaProto(): AdrBinaProto {
  return {
    id: 0,
    kodu: "",
    siteAdi: "",
    adi: "",
    binaKatSayisi: 0,
    daireSayisi: 0,
    isyeriSayisi: 0,
    yukseklik: 0,
    wkb: "",
  };
}

export const AdrBinaProto: MessageFns<AdrBinaProto> = {
  encode(message: AdrBinaProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.kodu !== "") {
      writer.uint32(18).string(message.kodu);
    }
    if (message.siteAdi !== "") {
      writer.uint32(26).string(message.siteAdi);
    }
    if (message.adi !== "") {
      writer.uint32(34).string(message.adi);
    }
    if (message.binaKatSayisi !== 0) {
      writer.uint32(41).double(message.binaKatSayisi);
    }
    if (message.daireSayisi !== 0) {
      writer.uint32(49).double(message.daireSayisi);
    }
    if (message.isyeriSayisi !== 0) {
      writer.uint32(57).double(message.isyeriSayisi);
    }
    if (message.yukseklik !== 0) {
      writer.uint32(65).double(message.yukseklik);
    }
    if (message.wkb !== "") {
      writer.uint32(74).string(message.wkb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AdrBinaProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAdrBinaProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kodu = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.siteAdi = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.adi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.binaKatSayisi = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.daireSayisi = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.isyeriSayisi = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.yukseklik = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.wkb = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AdrBinaProto {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      kodu: isSet(object.kodu) ? globalThis.String(object.kodu) : "",
      siteAdi: isSet(object.siteAdi) ? globalThis.String(object.siteAdi) : "",
      adi: isSet(object.adi) ? globalThis.String(object.adi) : "",
      binaKatSayisi: isSet(object.binaKatSayisi) ? globalThis.Number(object.binaKatSayisi) : 0,
      daireSayisi: isSet(object.daireSayisi) ? globalThis.Number(object.daireSayisi) : 0,
      isyeriSayisi: isSet(object.isyeriSayisi) ? globalThis.Number(object.isyeriSayisi) : 0,
      yukseklik: isSet(object.yukseklik) ? globalThis.Number(object.yukseklik) : 0,
      wkb: isSet(object.wkb) ? globalThis.String(object.wkb) : "",
    };
  },

  toJSON(message: AdrBinaProto): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.kodu !== "") {
      obj.kodu = message.kodu;
    }
    if (message.siteAdi !== "") {
      obj.siteAdi = message.siteAdi;
    }
    if (message.adi !== "") {
      obj.adi = message.adi;
    }
    if (message.binaKatSayisi !== 0) {
      obj.binaKatSayisi = message.binaKatSayisi;
    }
    if (message.daireSayisi !== 0) {
      obj.daireSayisi = message.daireSayisi;
    }
    if (message.isyeriSayisi !== 0) {
      obj.isyeriSayisi = message.isyeriSayisi;
    }
    if (message.yukseklik !== 0) {
      obj.yukseklik = message.yukseklik;
    }
    if (message.wkb !== "") {
      obj.wkb = message.wkb;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AdrBinaProto>, I>>(base?: I): AdrBinaProto {
    return AdrBinaProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AdrBinaProto>, I>>(object: I): AdrBinaProto {
    const message = createBaseAdrBinaProto();
    message.id = object.id ?? 0;
    message.kodu = object.kodu ?? "";
    message.siteAdi = object.siteAdi ?? "";
    message.adi = object.adi ?? "";
    message.binaKatSayisi = object.binaKatSayisi ?? 0;
    message.daireSayisi = object.daireSayisi ?? 0;
    message.isyeriSayisi = object.isyeriSayisi ?? 0;
    message.yukseklik = object.yukseklik ?? 0;
    message.wkb = object.wkb ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
