// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: adrYol.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface AdrYolResponse {
  isSuccess: boolean;
  message: string;
  statusCode: number;
  data: AdrYolProto[];
}

export interface AdrYolProto {
  id: number;
  genislik: number;
  seritSayisi: number;
  yapisi: string;
  tipi: string;
  kodu: string;
  adi: string;
  wkb: string;
}

function createBaseAdrYolResponse(): AdrYolResponse {
  return { isSuccess: false, message: "", statusCode: 0, data: [] };
}

export const AdrYolResponse: MessageFns<AdrYolResponse> = {
  encode(message: AdrYolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSuccess !== false) {
      writer.uint32(8).bool(message.isSuccess);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.statusCode !== 0) {
      writer.uint32(24).int32(message.statusCode);
    }
    for (const v of message.data) {
      AdrYolProto.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AdrYolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAdrYolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSuccess = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.statusCode = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data.push(AdrYolProto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AdrYolResponse {
    return {
      isSuccess: isSet(object.isSuccess) ? globalThis.Boolean(object.isSuccess) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      statusCode: isSet(object.statusCode) ? globalThis.Number(object.statusCode) : 0,
      data: globalThis.Array.isArray(object?.data) ? object.data.map((e: any) => AdrYolProto.fromJSON(e)) : [],
    };
  },

  toJSON(message: AdrYolResponse): unknown {
    const obj: any = {};
    if (message.isSuccess !== false) {
      obj.isSuccess = message.isSuccess;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.statusCode !== 0) {
      obj.statusCode = Math.round(message.statusCode);
    }
    if (message.data?.length) {
      obj.data = message.data.map((e) => AdrYolProto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AdrYolResponse>, I>>(base?: I): AdrYolResponse {
    return AdrYolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AdrYolResponse>, I>>(object: I): AdrYolResponse {
    const message = createBaseAdrYolResponse();
    message.isSuccess = object.isSuccess ?? false;
    message.message = object.message ?? "";
    message.statusCode = object.statusCode ?? 0;
    message.data = object.data?.map((e) => AdrYolProto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAdrYolProto(): AdrYolProto {
  return { id: 0, genislik: 0, seritSayisi: 0, yapisi: "", tipi: "", kodu: "", adi: "", wkb: "" };
}

export const AdrYolProto: MessageFns<AdrYolProto> = {
  encode(message: AdrYolProto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.genislik !== 0) {
      writer.uint32(17).double(message.genislik);
    }
    if (message.seritSayisi !== 0) {
      writer.uint32(25).double(message.seritSayisi);
    }
    if (message.yapisi !== "") {
      writer.uint32(34).string(message.yapisi);
    }
    if (message.tipi !== "") {
      writer.uint32(42).string(message.tipi);
    }
    if (message.kodu !== "") {
      writer.uint32(50).string(message.kodu);
    }
    if (message.adi !== "") {
      writer.uint32(58).string(message.adi);
    }
    if (message.wkb !== "") {
      writer.uint32(66).string(message.wkb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AdrYolProto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAdrYolProto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.genislik = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.seritSayisi = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.yapisi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tipi = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.kodu = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.adi = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.wkb = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AdrYolProto {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      genislik: isSet(object.genislik) ? globalThis.Number(object.genislik) : 0,
      seritSayisi: isSet(object.seritSayisi) ? globalThis.Number(object.seritSayisi) : 0,
      yapisi: isSet(object.yapisi) ? globalThis.String(object.yapisi) : "",
      tipi: isSet(object.tipi) ? globalThis.String(object.tipi) : "",
      kodu: isSet(object.kodu) ? globalThis.String(object.kodu) : "",
      adi: isSet(object.adi) ? globalThis.String(object.adi) : "",
      wkb: isSet(object.wkb) ? globalThis.String(object.wkb) : "",
    };
  },

  toJSON(message: AdrYolProto): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.genislik !== 0) {
      obj.genislik = message.genislik;
    }
    if (message.seritSayisi !== 0) {
      obj.seritSayisi = message.seritSayisi;
    }
    if (message.yapisi !== "") {
      obj.yapisi = message.yapisi;
    }
    if (message.tipi !== "") {
      obj.tipi = message.tipi;
    }
    if (message.kodu !== "") {
      obj.kodu = message.kodu;
    }
    if (message.adi !== "") {
      obj.adi = message.adi;
    }
    if (message.wkb !== "") {
      obj.wkb = message.wkb;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AdrYolProto>, I>>(base?: I): AdrYolProto {
    return AdrYolProto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AdrYolProto>, I>>(object: I): AdrYolProto {
    const message = createBaseAdrYolProto();
    message.id = object.id ?? 0;
    message.genislik = object.genislik ?? 0;
    message.seritSayisi = object.seritSayisi ?? 0;
    message.yapisi = object.yapisi ?? "";
    message.tipi = object.tipi ?? "";
    message.kodu = object.kodu ?? "";
    message.adi = object.adi ?? "";
    message.wkb = object.wkb ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
