<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Conduit3D.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure/Services/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.20" />
  </ItemGroup>

</Project>