<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Conduit3D.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure/" />
    <Folder Include="Infrastructure/Services/" />
  </ItemGroup>

</Project>